target: homework1
homework1: appendMeMore.c part2.c part3.c
	gcc appendMeMore.c -o appendMeMore -Wall
	gcc part2.c -o part2 -Wall
	gcc part3.c -o part3 -Wall

.PHONY: makeclean
makeclean:
	rm -f appendMeMore part2 part3
